[versions]
agp = "8.13.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"
androidx-lifecycle = "2.9.6"
binary-compatibility-generator = "0.18.1"
composeMultiplatform = "1.9.3"
coroutines = "1.10.2"
dokka = "2.1.0"
kermit = "2.0.8"
kotlin = "2.2.21"
ksp = "2.3.2"
ktlint-gradle = "14.0.1"
library-compileSdk = "36"
library-minSdk = "23"
maven-publish = "0.35.0"
room = "2.8.3"
sqlite = "2.6.1"
terpal = "2.2.20-2.0.1.PL"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqlite" }
terpal-runtime = { module = "io.exoquery:terpal-runtime", version.ref = "terpal" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-generator"}
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
room = { id = "androidx.room", version.ref = "room" }
terpal = { id = "io.exoquery.terpal-plugin", version.ref = "terpal" }
